name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install -g web-streams-polyfill
    
    - name: Node.js version info
      run: |
        node --version
        npm --version
        
    - name: Install vsce globally
      run: npm install -g @vscode/vsce

    - name: Build
      run: npm run compile

    - name: Package Extension
      run: |
        # Make sure the script is executable
        chmod +x scripts/package-extension.js
        # Run the script directly with polyfills
        node -r web-streams-polyfill/polyfill scripts/package-extension.js
      
    - name: Upload Extension
      uses: actions/upload-artifact@v4
      with:
        name: ghostwriter-extension
        path: "*.vsix" 