name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        # Set NODE_OPTIONS to load polyfills for all Node.js processes
        echo "NODE_OPTIONS=--require=web-streams-polyfill/polyfill" >> $GITHUB_ENV
        npm ci
    
    - name: Node.js version info
      run: |
        node --version
        npm --version
    
    - name: Build
      run: npm run compile
    
    - name: Package Extension with direct script
      run: |
        # Make sure the script is executable
        chmod +x scripts/package-extension.js
        # Run the script directly with polyfills
        node scripts/package-extension.js