name: Publish Extension

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version override (leave empty to use package.json)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          # Set NODE_OPTIONS to load polyfills for all Node.js processes
          echo "NODE_OPTIONS=--require=web-streams-polyfill/polyfill" >> $GITHUB_ENV
          npm ci
      
      - name: Node.js version info
        run: |
          node --version
          npm --version
      
      - name: Compile
        run: npm run compile
      
      - name: Package Extension with direct script
        run: |
          # Make sure the script is executable
          chmod +x scripts/package-extension.js
          # Run the script directly with polyfills
          node scripts/package-extension.js
      
      - name: Update version if provided
        if: github.event.inputs.version != ''
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Publish to Open VSX Registry
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }}
        continue-on-error: true 